### ISSUE TITLE
Test file is not writing byte-type.

### ISSUE THREAD

**Issue by JJack27** [abramhindle/CMPUT404-assignment-web-client#10]
I just found issues in `freetests.py`. In function `nothing_available()` and `echo_path_get()`, all their last line are writing `string` instead of `byte`. This issue could cause nothing will get send to the client. Please fix it.

**Comment by JJack27** [comment]
Also the strings in `req.body.find()`

**Comment by abramhindle** [comment]
https://github.com/abramhindle/CMPUT404-assignment-web-client/commit/ca993af20327386c57f9cc021a32587bf095da83 Does this solve the issue?

**Comment by JJack27** [comment]
Yes, this happens to every string send from test file.

**Comment by abramhindle** [comment]
OK closing the issue. Thanks.
